In [2]:
# paramètres : je les ai réunis ici afin d'avoir un code 'modulaire' : on peut choisir ce qu'on veut
# observer en fonction de paramètres listés ici

# pour le choix du matériau
cle_materiau = "mp-570213"

# propre à l'utilisateur
cle_utilisateur = "rEVEIFsc61iExKZbJ2QyepniwSgJ1m6W"

# le nombre de décimales qu'on veut voir pour les valeurs chiffrées
dec = 4

In [3]:
# téléchargement

from pymatgen.symmetry import analyzer as az
from pymatgen.ext.matproj import MPRester
from numpy import around

with MPRester(cle_utilisateur) as m:
    structure = m.get_structure_by_material_id(cle_materiau)

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [4]:
# on recupere les vecteurs de base, décrits via leurs angles et longueurs, pour la maille réciproque et la maille directe

# la structure qu'on va utiliser est une cellule primitive définie selon les principes de Setyawan, W., & Curtarolo, S. (2010)
# (information trouvée dans la documentation pymatgen)
structure = az.SpacegroupAnalyzer(structure).get_primitive_standard_structure()

maille = structure.lattice
maille_reciproque = maille.reciprocal_lattice

# on imprime les résultats
print('vecteurs du reseau de base :')
print(str(around(maille.abc,dec))+' [ångström] ')
print('angles :')
print(str(around(maille.angles,dec))+' [ångström] ')
print('\nvecteurs du reseau reciproque :')
print(str(around(maille_reciproque.angles,dec))+' [ångström] ')
print('angles :')
print(str(around(maille_reciproque.angles,dec))+' [ångström] ')

vecteurs du reseau de base :
[4.7947 4.7947 4.7947] [ångström] 
angles :
[60. 60. 60.] [ångström] 

vecteurs du reseau reciproque :
[109.4712 109.4712 109.4712] [ångström] 
angles :
[109.4712 109.4712 109.4712] [ångström] 


In [5]:
# on recupere le systeme crystallin, le groupe ponctuel et le type de maille

an = az.SpacegroupAnalyzer(structure)

print('systeme crystallin :')
print(an.get_crystal_system())
print('\ngroupe ponctuel :')
print(an.get_point_group_symbol())
print('\ntype de maille :')
print(an.get_lattice_type())

systeme crystallin :
cubic

groupe ponctuel :
-43m

type de maille :
cubic
